version: "2"
plugins:
  cppcheck:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  gnu-complexity:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
