if(NOT ARCH)
	set(ARCH "x86")
endif()
if(NOT TARGET)
	set(TARGET "pc")
endif()
set(CROSS_COMPILER "${ARCH}-${TARGET}-linux-gnu")
if(ARCH STREQUAL "x86")
	set(CROSS_COMPILER "i486-${TARGET}-linux-gnu")
endif()
