/**
	* StardustOS libc - (C) 2019 Tristan Ross
	*/
#pragma once

#define NEWLAND_ENOMEM 1
#define NEWLAND_ECHILD 2
#define NEWLAND_EEXIST 3
#define NEWLAND_ENODEV 4
#define NEWLAND_ENAMETOOLONG 5
#define NEWLAND_EIO 6
#define NEWLAND_EINVAL 7
#define NEWLAND_EINPROGRESS 8
#define NEWLAND_EINTR 9
#define NEWLAND_ENOSYS 10
#define NEWLAND_EOVERFLOW 11
#define NEWLAND_EISDIR 12
#define NEWLAND_EBUSY 13
#define NEWLAND_ENOENT 14
#define NEWLAND_EMFILE 15

#ifndef HAS_LIBC
#define ENOMEM NEWLAND_ENOMEM
#define ECHILD NEWLAND_ECHILD
#define EEXIST NEWLAND_EEXIST
#define ENODEV NEWLAND_ENODEV
#define ENAMETOOLONG NEWLAND_ENAMETOOLONG
#define EIO NEWLAND_EIO
#define EINVAL NEWLAND_EINVAL
#define EINPROGRESS NEWLAND_EINPROGRESS
#define EINTR NEWLAND_EINTR
#define ENOSYS NEWLAND_ENOSYS
#define EOVERFLOW NEWLAND_EOVERFLOW
#define EISDIR NEWLAND_EISDIR
#define EBUSY NEWLAND_EBUSY
#define ENOENT NEWLAND_ENOENT
#define EMFILE NEWLAND_EMFILE
#endif

extern int errno;