name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing to StardustOS, please look at CONTRIBUTING.md for some useful information.' 'first issue'
        pr-message: 'Thank you for contributing to StardustOS, please look at CONTRIBUTING.md for some useful information.' 'first pr'
